#!/usr/bin/env python

import sys

import rospy

from skeleton_pipeline.action_recognition import ActionRecognition


if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    ar = ActionRecognition()
    rospy.spin()
