#!/usr/bin/env python

import sys
from time import sleep

import rospy

from skeleton_pipeline.action_recognition import ActionRecognition


if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    rospy.init_node('action_recognition_node', anonymous=False)
    while (rospy.get_time() == 0):
        sleep(0.01)
    ar = ActionRecognition()
    ar.run()
