#!/usr/bin/env python

import sys

import rospy

from skeleton_pipeline.action_recognition import ActionRecognition


if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    rospy.init_node('action_recognition_node', anonymous=False)
    ar = ActionRecognition()
    ar.run()
