#!/usr/bin/env python

import sys

import rospy
from experiments.config import Config
from experiments.experimenter import Experimenter





# x TODO: storage of rosbag action data (start, end, filename, classification)
# x TODO: keeping track of time (subscribing to the simulation clock, launching events at predefined time steps)
# x TODO: start rosbag from experimenter
# x TODO: in worldstate: add trajectory calculus, generate labels for human movement relative to his node location as seen from the robot's perspective
# x TODO: generate human behavior events from observed movement
# x TODO: add distance metric and emergency stop
# x TODO: check reasoning
# x TODO: check experimenter

# . TODO: check pose detection

# . TODO: add pose for picking berries
# . TODO: add pose for call
# . TODO: add pose for cancel
# . TODO: add pose for stop
# . TODO: in bdi system: pause, start simulation, change simulation realtime factor


        # self.behaviours = {120: {"start": None,
        #                     "duration": None,
        #                     "filename": None,
        #                     "label": None,
        #                     "type": "action"},
        #                 240: {"label": None,
        #                     "type": "movement"},
        #                     }




if __name__ == '__main__':
    rospy.init_node("experiment_node")
    rospy.myargv(argv=sys.argv)
    rospy.loginfo("Experiment started")
    e = Experimenter()
    c = Config("thorvald_001")
    e.add_config(c)
    e.run()
