#!/usr/bin/env python
import sys

import rospy

from skeleton_pipeline.skeleton_logger import SkeletonLogger

if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    se = SkeletonLogger()
    rospy.spin()
