#!/usr/bin/env python

import sys

import rospy

from skeleton_pipeline.skeleton_converter import SkeletonConverter

if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    sm = SkeletonConverter()
    rospy.spin()
