#!/usr/bin/env python

import sys

import rospy
from skeleton_pipeline.skeleton_comparator import SkeletonComparator


if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    sm = SkeletonComparator()
    rospy.spin()
