#!/usr/bin/env python
import sys

import rospy

from skeleton_pipeline.skeleton_extractor import SkeletonExtractor

if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    se = SkeletonExtractor()
    se.service.start()
    rospy.spin()
