#!/usr/bin/env python

import sys

import rospy

from skeleton_pipeline.skeleton_stabilizer import SkeletonStabilizer

if __name__ == '__main__':
    rospy.myargv(argv=sys.argv)
    sm = SkeletonStabilizer()
    rospy.spin()
